require:
  - rubocop-rspec
  
Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Rails/Output:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Max: 30
